# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'strainer' do
  watch %r{^spec/(.+).rb%}
  watch %r{^recipes/(.+).rb%}
  # Comment the above and uncomment this line if you are using Strainer in standalone mode
  # Make sure to set the :standalone option above!
  # watch %r{(.+)%}
end