Vagrant.configure("2") do |config|

  config.berkshelf.enabled = true
  config.omnibus.chef_version = :latest

  config.vm.box = "Opscode-CentOS-6.4-x86_64"
  config.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box"

  config.vm.hostname = "{{cookiecutter.cookbook_name}}-vagrant"

  ci.vm.provision :chef_solo do |chef|
    chef.run_list = [
                     "recipe[{{cookiecutter.cookbook_name}}]"
                    ]
  end
end
